In [1]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer

In [2]:
ls

 Volume in drive D has no label.
 Volume Serial Number is A82D-86F7

 Directory of D:\Data_Analysis\Day3_Data_Preprocessing

13-03-2026  21:00    <DIR>          .
13-03-2026  20:28    <DIR>          ..
13-03-2026  21:00    <DIR>          .ipynb_checkpoints
13-03-2026  17:01            27,835 1.Learning_Preprocessing.ipynb
13-03-2026  20:29            19,971 2.DataAnalysis_Numeric.ipynb
13-03-2026  20:29            36,927 3.NullValuesHandling.ipynb
13-03-2026  21:00            33,226 4.DataAnalysis_withConditions.ipynb
13-03-2026  21:00                72 5.Group_by.ipynb
13-03-2026  18:00               218 Data.csv
13-03-2026  20:39    <DIR>          Google_Playstore
               6 File(s)        118,249 bytes
               4 Dir(s)  361,884,590,080 bytes free

In [4]:
df = pd.read_csv("Google_Playstore/googleplaystore.csv")
df = df.dropna()

In [5]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

## Q1.Name the apps that are in ART_AND_DESIGN with rating more then 4.5 in descending order WRT Ratings?

In [6]:
df_pr = df[df['Category'] == 'ART_AND_DESIGN']
df_pr = df_pr[df_pr['Rating'] > 4.5]

df_pr.sort_values( by = 'Rating', ascending = True ).head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
13,Mandala Coloring Book,ART_AND_DESIGN,4.6,4326,21M,"100,000+",Free,0,Everyone,Art & Design,"June 26, 2018",1.0.4,4.4 and up
19,ibis Paint X,ART_AND_DESIGN,4.6,224399,31M,"10,000,000+",Free,0,Everyone,Art & Design,"July 30, 2018",5.5.4,4.1 and up
46,Install images with music to make video withou...,ART_AND_DESIGN,4.6,1070,26M,"100,000+",Free,0,Everyone,Art & Design,"November 14, 2017",1.6,4.1 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
4764,X Launcher Prime: With OS Style Theme & No Ads,ART_AND_DESIGN,4.7,149,3.5M,"1,000+",Paid,$1.99,Everyone,Art & Design,"July 30, 2018",1.2.2,4.1 and up

## Q2.Which category is having maximum average rating Descending order?

In [14]:
df.groupby('Category')['Rating'].mean().sort_values(ascending=False)

Category
EVENTS                 4.435556
EDUCATION              4.389032
ART_AND_DESIGN         4.377049
BOOKS_AND_REFERENCE    4.346067
PERSONALIZATION        4.335256
PARENTING              4.300000
GAME                   4.286326
BEAUTY                 4.278571
HEALTH_AND_FITNESS     4.277104
SHOPPING               4.259664
SOCIAL                 4.255598
WEATHER                4.244000
SPORTS                 4.223511
PRODUCTIVITY           4.211396
HOUSE_AND_HOME         4.197368
FAMILY                 4.192383
PHOTOGRAPHY            4.192114
AUTO_AND_VEHICLES      4.190411
MEDICAL                4.189143
LIBRARIES_AND_DEMO     4.179688
FOOD_AND_DRINK         4.166972
COMMUNICATION          4.158537
COMICS                 4.155172
NEWS_AND_MAGAZINES     4.132189
FINANCE                4.131889
ENTERTAINMENT          4.126174
BUSINESS               4.121452
TRAVEL_AND_LOCAL       4.109292
LIFESTYLE              4.094904
VIDEO_PLAYERS          4.063750
MAPS_AND_NAVIGATION    4.051613
TOOLS                  4.047203
DATING                 3.970769
Name: Rating, dtype: float64

## Q3.How many paid apps are there in each category in Descending Order?

In [13]:
df_pr = df[df['Type'] == 'Paid']

df_pr.groupby('Category').count()['Type'].sort_values(ascending = False)

Category
FAMILY                 161
MEDICAL                 88
GAME                    77
PERSONALIZATION         66
TOOLS                   63
COMMUNICATION           22
SPORTS                  22
PRODUCTIVITY            18
LIFESTYLE               18
PHOTOGRAPHY             18
FINANCE                 13
HEALTH_AND_FITNESS      12
BUSINESS                11
BOOKS_AND_REFERENCE      8
TRAVEL_AND_LOCAL         8
WEATHER                  7
MAPS_AND_NAVIGATION      5
EDUCATION                4
DATING                   4
VIDEO_PLAYERS            4
ART_AND_DESIGN           3
PARENTING                2
NEWS_AND_MAGAZINES       2
FOOD_AND_DRINK           2
SHOPPING                 2
SOCIAL                   2
ENTERTAINMENT            2
AUTO_AND_VEHICLES        1
Name: Type, dtype: int64